import { Lato } from 'next/font/google'
import './globals.css'
import SiteHeader from '@/components/header/SiteHeader'
// import SiteFooter from '@/components/Footer/SiteFooter'


const lato = Lato({
  weight: ['100', '300', '400', '700', '900'],
  subsets: ['latin'],
  display: 'swap',
  //👇 Add variable to our object
  variable: '--font-lato',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={lato.className}>
            <SiteHeader />
            <main className="flex min-h-screen flex-col items-center justify-between">
              {children}
            </main>
            
            {/* <SiteFooter /> */}
      </body>
    </html>
  )
}
